# Generated by Django 4.2.7 on 2023-12-01 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 15, 29, 7, 654178, tzinfo=datetime.timezone.utc)),
        ),
    ]
