# Generated by Django 4.2.7 on 2023-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager_app', '0002_alter_expense_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
